peppelinux/draft-demarco-acme-openid-federation

- draft-demarco-acme-openid-federation.md
This clarifies which keys can be used to satisfy the new ACME challenge
type. Along with the preexisting text that "The CSR MUST include the
public key, attested within the Trust Chain, used by the Requestor to
satisfy the Issuer's challenge.", this also defines which keys can be
included in the eventual certificate -- I made some editorial changes to
highlight this requirement.
> Define which keys can be used to satisfy a challenge.

- draft-demarco-acme-openid-federation.md
Specifically, require the certificate to include the same public key
used to satisfy the challenge (duplicating text elsewhere), and specify
how the Entity ID is included in the certificate.
> Specify requirements on CSR and Certificate.

- draft-demarco-acme-openid-federation.md
This PR alignes terminology, in particular
- replaces Entity Statement with Subordinate Statement, to be more clear about the type of Entity Statement used and therefore aligned with the current Federation Draft
- remove the word "Connect" in OpenID Federation
- uses the term Certificate Issuer instead of Issuer alone
- use more normative language
- removes some useless remark
Generally this PR facilitate the further works of:
- reducing duplication, in the text we might see some duplicated words about the check and the overall verification mechanism
- introducing sequence diagrams
> fix: editorials and terminology used

- draft-demarco-acme-openid-federation.md
I pulled `OpenIdFederationEntityId` out of thin air, we should ensure `id` is capitalized the way we want, and consider pulling the second out to `identifier` to match 1.3.6.1.5.5.7.8.3 `id-on-permanentIdentifier`, but this is only intended as a first stab.
> Grammar, spelling, and an initial IANA Considerations section

- draft-demarco-acme-openid-federation.md
This section is somewhat awkwardly worded. Reword to make it clear that we're taking the ACME directory and putting it in the entity configuration.
> Reword metadata section for clarity

- draft-demarco-acme-openid-federation.md
This PR
- fix the inconsistency we have mentioning the federation entity keys instead of all the jwks made available through the entity configuration
- Resolves https://github.com/peppelinux/draft-demarco-acme-openid-federation/issues/18
> fix: all the the keys and not federation entity keys only

- draft-demarco-acme-openid-federation.md
Precondition 4 is always true, and doesn't seem applicable to the statement we're making here. I also reworded slightly.
In Overview I also fix the formatting slightly--the indentation was too deep causing it to be rendered as a code block.
> editorial: reword discovery for clarity

- draft-demarco-acme-openid-federation.md
This PR clarifies that the Issuer MUST implement ACME and it might match the trust anchor or one of its intermediates
> fix: generalization of the role of the Issuer within the federation

- draft-demarco-acme-openid-federation.md
As mentioned in #38, the entity identifier is implicitly known from the parent authorization of the challenge. Thus, it is not necessary to include the identifier in the challenge response.
> Remove entity_identifier from challenge response

- draft-demarco-acme-openid-federation.md
This addresses #13. I introduce one new problem type for the problem details returned in ACME error responses. This encapsulates an OAuth error code, and thus provides us a way to translate all existing OpenID Federation error codes into an ACME error response. This also requires some additional IANA considerations, in order to set up a registration justifying the `urn:ietf:params:` URI.
> Specify how errors are formatted

- draft-demarco-acme-openid-federation.md
This updates the description of the challenge type to clarify that it only proves control of a federation entity, not a domain.
> Challenge proves control of entity, not domain

- draft-demarco-acme-openid-federation.md
This changes the challenge method to include a signature of the key authorization, instead of a signature of the token. I also added a corresponding blurb to the security considerations section. Closes #42.
> Sign key authorization instead of token

- draft-demarco-acme-openid-federation.md
We can't check CAA for non-dnsName identifiers. While the Entity Configuration is marked non-normative, having CAA in there will be confusing.
> CAA is irrelevant

- draft-demarco-acme-openid-federation.md
This rewrites the Discovery Preconditions section, splitting it in two and moving some other parts to neighboring sections. The text no longer distinguishes between leaf and intermediate federation entities. The options of no discovery/discovery by entity type alone/discovery with trust marks are laid out in the new discovery section. ACME account creation is moved to the overview section, and the procedure there is cleaned up a bit. Closes #48.
> Rewrite Discovery Preconditions section

- draft-demarco-acme-openid-federation.md
The existing text about how the ACME requestor should sign the ACME issuer's challenge token had several ambiguities and problems. This change is stacked on top of #53: the problems I am describing are orthogonal to that change. Below, I will reference text assuming #53 is merged.
> a base64url encoding of a JWT
- "a base64url encoding" isn't specific enough. It makes more sense to me to explicitly require JWS Compact Serialization here, which is consistent with the requirement in OpenID Federation ([1]).
- If this is a signature, then presumably what we are constructing is a JWS. A JWS is a JWT, so this wasn't wrong, but it seems more clear to explicitly say JWS, as otherwise it's unclear how the implementation should represent a signature.
> It is REQUIRED that this JWT include a `kid` …
> Clarify construction of signed challenge

- draft-demarco-acme-openid-federation.md
Section 3 helpfully formalizes the notions of ACME issuers and requestors. However, in the issuer metadata (section 6.4.1), we define the OpenID Federation entity type `acme_provider`. There's no need to introduce two notions of "issuer" and "provider" that are basically synonymous, so in this commit we use "issuer" (in prose) or `acme_issuer` (in JSON documents) consistently.
> Converge on "ACME issuer" rather than "provider"

- draft-demarco-acme-openid-federation.md
The example of a JWKS included in an acme_requestor metadata block should not include `iss`, `sub` or `iat`. The protocol text says that the JWK set should be published according to OIDF 5.2.1, which describes metadata keys `signed_jwks_uri`, `jwks_uri` and `jwks`. Only in the first case are `iss`, `sub` or `iat` necessary. Including them when the key set is inline in the metadata is just confusing, because they de facto must have the same `sub` as the enclosing entity configuration.
> Fix example acme_requestor JWKS

- diagrams/plantuml
- draft-demarco-acme-openid-federation.md
The diagram shows the requestor POSTing to the challenge at L326, and then the issuer responds at L332 indicating validation has begun. The existing diagram also illustrates a response from issuer to requestor at L372, but that isn't correct: the requestor's request was previously responded to at L332. Validation happens asynchronously from the POST to the challenge, and the requestor learns of its success or failure by polling the authz.
I'm explaining this rather laboriously so that reviewers can let me know if I've misunderstood how ACME works.
> Remove non-existent response from sequence diagram

- draft-demarco-acme-openid-federation.md
Fixes #59.
This pulls the definition of `openid-federation`'s Identifier Type into its own heading, moving it slightly up the page, to make it more clear it's there and happening (like with https://datatracker.ietf.org/doc/html/draft-ietf-acme-onion-07#name-identifier and https://datatracker.ietf.org/doc/html/rfc8738#name-ip-identifier).
Then it adds the necessary `MUST NOT` conditions on usage, taking some inspiration from https://datatracker.ietf.org/doc/html/rfc8738#section-7 and https://datatracker.ietf.org/doc/html/draft-ietf-acme-onion-07#section-3.1.1.
> Restrict the OpenID Federation challenge type and identifier to each other.

- draft-demarco-acme-openid-federation.md
This relaxes some restrictions on certificates. Putting the entity ID in a subject alternative name is now optional. The requirement to have only one identifier per order is deleted in two places. Closes #54 and #38.
> Loosen certificate profile

- draft-demarco-acme-openid-federation.md
This removes a `SHOULD` that told issuers to monitor entity configuration post-issuance and revoke when keys are removed. Closes #70.
> Don't revoke upon federation metadata change

- draft-demarco-acme-openid-federation.md
The strings in the `trust_chain` array are not base64url-encoded data, but compact form JWTs.
> Rephrase description of trust chain

- draft-demarco-acme-openid-federation.md
This moves responsibility for publication of certificates from the OIDFed hierarchy to RFC6962/RFC9162 certificate transparency logs, and otherwise marks it as out-of-scope.
I am hoping this is unambiguous that how a Certificate Issuer does it is for policy, to include whether they submit pre-certificates or final certificates, or if they embed SCTs or transmit them some other way, or even use CTv1 vs CTv2.
Fixes #65.
> Revise publication to rely on Certificate Transparency

- draft-demarco-acme-openid-federation.md
I ran the draft through the idnits and idnits3 tools, and fixed some of the issues it flagged.
* I removed references from the abstract section
* After doing so, we no longer use RFC2818. Besides, RFC 2818 has been obsoleted by RFC 9110. This isn't directly important to the draft, so I deleted the reference.
* I fixed some references that were using Markdown links instead of the double curly brace syntax. These seem to look the same in text and HTML form, but they were producing a warning about the XML reference's text form.
> Fix idnits

- draft-demarco-acme-openid-federation.md
Moves "Overview" up to the header section of "Protocol Flow" and collapses some redundant sections into it.
> reorganize protocol overview

- draft-demarco-acme-openid-federation.md
Some of #85 was addressed in #88. This commit addresses my remaining gripes:
- allow a `urn:ietf:params:acme:error:openIDFederationEntity` error to contain any `error_code` allowed by OPENID-FED, not just `invalid_trust_chain`
- Refer to OPENID-FED for permitted error codes, rather than IANA-OAUTH. OPENID-FED adds a dozen or so error codes to those in IANA-OAUTH ([1]).
- `:openIDFederationEntity` errors SHOULD include `error_code`, but if they do, `error_code` MUST be one of the ones defined in OPENID-FED.
[1]: https://openid.net/specs/openid-federation-1_0.html#section-8.9
Resolves #85
> improve discussion of new error type URN

- draft-demarco-acme-openid-federation.md
This draft doesn't need to explain anything about a `newOrder` request beyond defining the new identifier type for OIDF. This commit deletes that section. We also add a non-normative example of an `openid-federation` ACME identifier.
Resolves #100
> delete redundant newOrder section

- draft-demarco-acme-openid-federation.md
Add terminology section entries for "ACME Identifier" and "Entity" Identifier". The latter refers to the definition in the OIDF spec.
Sadly there is no crisp definition of "identifier" in ACME (!), so for the former, we just link to RFC 8555.
Audit all existing usages of "identifier" and replace with either "ACME Identifier" or "Entity Identifier", as appropriate, to make it clear which we're talking about in any given sentence.
Resolves #103
> Be explicit about ACME vs. OIDF Entity Identifiers

- draft-demarco-acme-openid-federation.md
- Don't allow `notAfter` to go past the trust chain's `exp` (#101)
- Define an ACME error type for certs whose validity period can't be satisfied
- Don't discuss revocation at all (#110)
resolves #101
resolves #110
> cert lifecycle fixes
